// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using gs_bluehorizon_dotnet.Data;

#nullable disable

namespace gs_bluehorizon_dotnet.Migrations
{
    [DbContext(typeof(BlueHorizonDbContext))]
    partial class BlueHorizonDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("gs_bluehorizon_dotnet.Models.VoluntarioPerfil", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("id_perfil");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("PessoaId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<int>("QntdLixo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("qntdlixoretirado_perfil");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId")
                        .IsUnique();

                    b.ToTable("voluntario_perfil");
                });

            modelBuilder.Entity("gs_bluehorizon_dotnet.Models.VoluntarioPessoa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("id_pessoa");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BairroEndereco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("bairro_end");

                    b.Property<string>("CepEndereco")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR2(8)")
                        .HasColumnName("cep_end");

                    b.Property<string>("CidadeEndereco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("cidade_end");

                    b.Property<string>("CpfPessoa")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("NVARCHAR2(11)")
                        .HasColumnName("cpf_pessoa");

                    b.Property<DateTime>("DtnascPessoa")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dtnasc_pessoa");

                    b.Property<string>("EstadoEndereco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("estado_end");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nome_pessoa");

                    b.Property<string>("NumEndereco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("num_end");

                    b.Property<string>("PaisEndereco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("pais_end");

                    b.Property<string>("RuaEndereco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("rua_end");

                    b.Property<string>("SenhaPessoa")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("senha_pessoa");

                    b.HasKey("Id");

                    b.ToTable("voluntario_pessoa");
                });

            modelBuilder.Entity("gs_bluehorizon_dotnet.Models.VoluntarioPerfil", b =>
                {
                    b.HasOne("gs_bluehorizon_dotnet.Models.VoluntarioPessoa", "VoluntarioPessoa")
                        .WithOne("Perfil")
                        .HasForeignKey("gs_bluehorizon_dotnet.Models.VoluntarioPerfil", "PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VoluntarioPessoa");
                });

            modelBuilder.Entity("gs_bluehorizon_dotnet.Models.VoluntarioPessoa", b =>
                {
                    b.Navigation("Perfil");
                });
#pragma warning restore 612, 618
        }
    }
}
